master:
  - test_master_spec.rb
etcd:
  - test_etcd_spec.rb
nfs:
  - test_nfs_spec.rb
loadbalancer:
  - test_loadbalancer_spec.rb
stackstorm:
  - test_stackstorm_spec.rb
auth:
  - test_auth_spec.rb
minion:
  - test_minion_spec.rb
